/**
 * DATABASE TYPE DEFINITIONS
 * 
 * Auto-generated by Prisma after running: npx prisma generate
 * Import types from @prisma/client instead of defining here
 */

export type DatabaseTypes = 'Run: npx prisma generate to create types';